spring:
    datasource:
        password: 1423
        url: jdbc:mysql://localhost:3306/rest_api_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    resources:
        static-locations: file:/upload
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
            enabled: true

cloudinary:
    cloud_name: "${CLOUD_NAME}"
    api_key: "${API_KEY}"
    api-secret: "${CLOUDINARY_SECRET}"


